config/routes.rb
Otwarchive::Application.routes.draw do

  devise_for :admin,
             module: 'admin',
             only: :sessions,
             controllers: { sessions: 'admin/sessions' },
             path_names: {
               sign_in: 'login',
               sign_out: 'logout'
             }

  devise_scope :user do
    get 'signup(/:invitation_token)' => 'users/registrations#new', as: 'signup'
  end

  devise_for :users,
             module: 'users',
             controllers: {
                sessions: 'users/sessions',
                registrations: 'users/registrations'
              },
              path_names: {
                sign_in: 'login',
                sign_out: 'logout'
              }

  get '/403', to: 'errors#403'
  get '/404', to: 'errors#404'
  get '/422', to: 'errors#422'
  get '/500', to: 'errors#500'
  get '/auth_error', to: 'errors#auth_error'

  get 'downloads/:download_prefix/:download_authors/:id/:download_title.:format' => 'downloads#show', as: 'download'

  namespace :opendoors do
    resources :tools, only: [:index] do
      collection do
        post :url_update
      end
    end
    resources :external_authors do
      member do
        post :forward
      end
    end
  end

  resources :invitations
  resources :user_invite_requests
  resources :invite_requests do
    collection do
      get :manage
      post :reorder
      get :status
    end
  end

  get 'claim/:invitation_token' => 'external_authors#claim', as: 'claim'
  post 'complete_claim/:invitation_token' => 'external_authors#complete_claim', as: 'complete_claim'

  resources :media do
    resources :fandoms
  end
  resources :fandoms do
    collection do
      get :unassigned
    end
    get :show
  end
  resources :tag_wranglings do
    collection do
      post :wrangle
      get :discuss
    end
  end
  resources :tag_wranglers
  resources :unsorted_tags do
    collection do
      post :mass_update
    end
  end
  resources :tags do
    member do
      get :feed
      post :mass_update
      get :remove_association
      get :wrangle
      get :reindex
    end
    collection do
      get :show_hidden
      get :search
    end
    resources :works
    resources :bookmarks
    resources :comments
  end

  resources :tag_sets, controller: 'owned_tag_sets' do
    resources :nominations, controller: 'tag_set_nominations' do
      collection do
        put  :update_multiple
        delete :destroy_multiple
        get :confirm_destroy_multiple
      end
      member do
        get :confirm_delete
      end
    end
    resources :associations, controller: 'tag_set_associations', only: [:index] do
      collection do
        put :update_multiple
      end
    end
    member do
      get :batch_load
      put :do_batch_load
      get :confirm_delete
    end
    collection do
      get :show_options
    end
  end
  resources :tag_nominations, only: [:update]

  resources :tag_wrangling_requests, only: [:index] do
    collection do
      patch :update_multiple
    end
  end

  resources :admins
  resources :admin_posts do
    resources :comments
  end

  namespace :admin do
    resources :activities, only: [:index, :show]
    resources :banners do
      member do
        get :confirm_delete
      end
    end
    resources :blacklisted_emails, only: [:index, :new, :create, :destroy]
    resources :settings
    resources :skins do
      collection do
        get :index_rejected
        get :index_approved
      end
    end
    resources :spam, only: [:index] do
      collection do
        post :bulk_update
      end
    end
    resources :user_creations, only: [:destroy] do
      member do
        put :hide
        put :set_spam
      end
    end
    resources :users, controller: 'admin_users' do
      member do
        get :confirm_delete_user_creations
        post :destroy_user_creations
        post :activate
        post :send_activation
        get :check_user
      end
      collection do
        get :bulk_search
        post :bulk_search
        post :update_user
      end
    end
    resources :invitations, controller: 'admin_invitations' do
      collection do
        post :invite_from_queue
        post :grant_invites_to_users
        get :find
      end
    end
    resources :api
  end

  post '/admin/api/new', to: 'admin/api#create'

  resources :people, only: [:index] do
    collection do
      get :search
    end
  end

  resources :passwords, only: [:new, :create]

  resources :users, except: [:new, :create] do
    member do
      get :browse
      get :change_email
      post :changed_email
      get :change_password
      post :changed_password
      get :change_username
      post :changed_username
      post :end_first_login
      post :end_banner
      post :end_tos_prompt
    end
    resources :assignments, controller: "challenge_assignments", only: [:index] do
      collection do
        patch :update_multiple
      end
      member do
        get :default
      end
    end
    resources :claims, controller: "challenge_claims", only: [:index]
    resources :bookmarks
    resources :collection_items, only: [:index, :update, :destroy] do
      collection do
        patch :update_multiple
      end
    end
    resources :collections, only: [:index]
    resources :comments do
      member do
        put :approve
        put :reject
      end
    end
    resources :external_authors do
      resources :external_author_names
    end
    resources :favorite_tags, only: [:create, :destroy]
    resources :gifts, only: [:index]
    resource :inbox, controller: "inbox" do
      member do
        get :reply
        post :delete
      end
    end
    resources :invitations do
      collection do
        post :invite_friend
      end
      collection do
        get :manage
      end
    end
    resources :nominations, controller: "tag_set_nominations", only: [:index]
    resources :preferences, only: [:index, :update]
    resource :profile, only: [:show], controller: "profile"
    resources :pseuds do
      resources :works
      resources :series
      resources :bookmarks
    end
    resources :readings do
      collection do
        post :clear
      end
    end
    resources :related_works
    resources :series do
      member do
        get :manage
      end
      resources :serial_works
    end
    resources :signups, controller: "challenge_signups", only: [:index]
    resources :skins, only: [:index]
    resources :stats, only: [:index]
    resources :subscriptions, only: [:index, :create, :destroy]
    resources :tag_sets, controller: "owned_tag_sets", only: [:index]
    resources :works do
      collection do
        get :drafts
        get :collected
        get :show_multiple
        post :edit_multiple
        patch :update_multiple
        post :delete_multiple
      end
    end
  end

  resources :works do
    collection do
      post :import
      get :search
    end
    member do
      get :preview
      post :post
      put :post_draft
      get :navigate
      get :edit_tags
      get :preview_tags
      patch :update_tags
      get :mark_for_later
      get :mark_as_read
      get :confirm_delete
      get :reindex
    end
    resources :bookmarks
    resources :chapters do
      collection do
        get :manage
        post :update_positions
      end
      member do
        get :preview
        post :post
        get :confirm_delete
      end
      resources :comments
    end
    resources :collections
    resources :collection_items
    resources :comments do
      member do
        put :approve
        put :reject
      end
      collection do
        get :unreviewed
        put :review_all
      end
    end
    resources :kudos, only: [:index]
    resources :links, controller: "work_links", only: [:index]
  end

  resources :chapters do
    member do
      get :preview
      post :post
    end
    resources :comments
  end

  resources :external_works do
    collection do
      get :compare
      post :merge
      get :fetch
    end
    resources :bookmarks
    resources :related_works
  end

  resources :related_works
  resources :serial_works
  resources :series do
    member do
      get :confirm_delete
      get :manage
      post :update_positions
    end
    resources :bookmarks
  end

  resources :gifts, only: [:index] do
    member do
      post :toggle_rejected
    end
  end

  resources :collections do
    collection do
      get :list_challenges
      get :list_ge_challenges
      get :list_pm_challenges
    end
    member do
      get :confirm_delete
    end
    resource :profile, controller: "collection_profile"
    resources :collections
    resources :works
    resources :gifts
    resources :bookmarks
    resources :media
    resources :fandoms
    resources :people
    resources :prompts
    resources :tags do
      resources :works
    end
    resources :participants, controller: "collection_participants" do
      collection do
        get :add
        get :join
        patch :update
      end
    end
    resources :items, controller: "collection_items" do
      collection do
        patch :update_multiple
      end
    end
    resources :signups, controller: "challenge_signups" do
      collection do
        get :summary
      end
      member do
        get :confirm_delete
      end
    end
    resources :assignments, controller: "challenge_assignments", except: [:new, :edit, :update] do
      collection do
        get :confirm_purge
        get :generate
        put :set
        post :purge
        get :send_out
        put :update_multiple
        get :default_all
      end
    end
    resources :claims, controller: "challenge_claims" do
      collection do
        patch :set
        get :purge
      end
    end
    resources :potential_matches do
      collection do
        get :generate
        get :cancel_generate
        get :regenerate_for_signup
      end
    end
    resources :requests, controller: "challenge_requests"

app/views/tags/_search_form.html.erb
<% @query = {} unless @query %>
<%= form_tag url_for(:controller => 'tags', :action => 'search'), :class => 'simple search', :role => "search", :method => :get do %>
<fieldset class="search tags">
  <legend>Search tags</legend>
  <p>
	<%= link_to_help "tag-search-text-help" %> <%= text_field_tag "query[name]", @query[:name], :id => 'tag_search', :title => ts("Enter tags")  %>
    <%= select_tag "query[type]", options_for_select([""] + Tag::USER_DEFINED, @query[:type]), :title => ts("Choose type") %>
    <label for="canonical" class="action">Canonical <%= check_box_tag "query[canonical]", true, @query[:canonical], :id => 'canonical' %></label>
  <span class="submit actions"><%= submit_tag ts("Search tags"), :name => nil %></span>
</p>
</fieldset>
<% end %>

app/views/tags/edit.html.erb
<!--Descriptive page name, messages and instructions-->
<h2 class="heading"><%= ts("Edit %{tag_link} Tag", :tag_link => link_to_tag(@tag)).html_safe %></h2>
<%= error_messages_for :tag %>
<!--/descriptions-->

<!--subnav-->
<p class="navigation actions" role="navigation"><%= tag_comment_link(@tag) %></p>
<!--/subnav-->

<!--main content-->

<%= form_for @tag, :as => :tag, :url => { :action => "update", :id => @tag}, :html => { :method => :put } do |f| %>

  <fieldset>
    <legend><%= ts("Tag Info") %></legend>
    <h3 class="landmark heading"><%= ts("Tag Info") %></h3>

    <dl>
      <dt><%= f.label :name, ts('Name') %></dt>
      <dd>
        <% if Tag::USER_DEFINED.include?(@tag.class.name) || (@tag[:type] == 'Media' && logged_in_as_admin?) %>
          <%= f.text_field :name, :size => (@tag.name.length + 5) %>
          <% unless logged_in_as_admin? %>
            <p><%= ts("Only changes to capitalization and diacritic marks are permitted.") %></p>
          <% end %>
        <% else %>
          <strong><%= @tag.name %></strong>
        <% end %>
      </dd>

      <% if @tag.type.to_s == 'Fandom' %>
        <dt><%= f.label :sortable_name, ts('Name To Use For Alphabetical Sorting') %></dt>
        <dd>
          <%= f.text_field :sortable_name, :size => (@tag.sortable_name.length + 5) %>
        </dd>
      <% end %>

      <dt><%= ts('Category') %></dt>
      <dd>
        <% if @tag.can_change_type? %>
          <%= f.select :type, options_for_select(%w(Fandom Character Relationship Freeform UnsortedTag), @tag.type.to_s) %>
        <% else %>
          <strong><%= @tag.type %></strong>
        <% end %>
      </dd>

      <% if @wranglers %>
        <dt><%= ts('Wranglers') %></dt>
        <dd><%= wrangler_list(@wranglers, @tag) %></dd>
      <% end %>

      <dt><%= f.label :canonical, ts('Canonical') %></dt>
      <dd>
        <%= f.check_box("canonical", :disabled => !(logged_in_as_admin? || Tag::USER_DEFINED.include?(@tag.class.name)) || !@tag.mergers.empty? || !@tag.children.empty? ) %>&nbsp;
        <p><%= ts("This is the official name for the %{tag_class_name}", :tag_class_name => @tag.class.name) %></p>
        <% if logged_in_as_admin? && Tag::USER_DEFINED.include?(@tag.class.name) && @tag.canonical? && (!@tag.mergers.empty? || !@tag.children.empty?) %>
          <p class="actions" role="navigation"><%= link_to ts('Make tag non-canonical and unhook all associations'), {:controller => :tags, :action => :update, 'tag[canonical]' => 0, :id => @tag}, :method => :put, data: {confirm: "Are you sure?"} %></p>
        <% end %>
      </dd>

      <% if @tag.is_a?(Rating)%>
        <dt><%= f.label :adult, ts('Adult') %></dt>
        <dd><%= f.check_box("adult", :disabled => !logged_in_as_admin? )%>&nbsp;<%= ts('This tag indicates adult content.') %></dd>
      <% end %>

      <% if Tag::USER_DEFINED.include?(@tag[:type]) %>
        <dt><%= f.label :syn_string, ts('Synonym of') %></dt>
        <dd>
          <%= f.text_field :syn_string, autocomplete_options("tag?type=#{@tag.type.downcase}", :class => 'autocomplete tags', :autocomplete_token_limit => 1) %>
          <p><%= ts("Choose an existing tag or add a new tag name here to create a new canonical and make this tag its synonym.") %></p>
          <% if @tag.merger %>
            <p class="actions" role="navigation">
              <%= link_to ts("Edit %{tag_name}", :tag_name => @tag.merger.name), edit_tag_path(@tag.merger) %>
            </p>
          <% elsif @tag.canonical? %>
            <p class="important caution notice"><%= ts("Adding a synonym to a canonical tag will make it non-canonical and move its associations to the other tag. (Be careful with this!)") %></p>
          <% end %>
        </dd>
      <% end %>

      <dt><%= f.label :unwrangleable %></dt>
      <dd>
        <%= f.check_box(:unwrangleable, :disabled => (@tag.class.name == "UnsortedTag")) %>&nbsp;
        <p><%= ts("This tag will never be merged or made canonical and should not be included on wrangling pages.") %></p>
      </dd>
    </dl>
  </fieldset>

  <% if (Tag::USER_DEFINED + ['Media']).include?(@tag[:type]) %>
    <fieldset>
      <legend><%= ts("Parent Tags") %></legend>
      <h3 class="landmark heading"><%= ts("Parent Tags") %></h3>
      <dl>
        <% @tag.parent_types.each do |tag_type| %>
          <% if tag_type == 'Fandom' && !@suggested_fandoms.blank? %>
            <dt><%= ts("Suggested Fandoms") %>:</dt>
            <dd>
            <% @suggested_fandoms[0..19].in_groups(2, false) do |fandom_list| %>
              <ul class="tags commas">
              <% for tag in fandom_list %>
                <li><%= link_to_edit_tag(tag) %></li>
              <% end %>
              </ul>
            <% end %>
            <% if @suggested_fandoms.length > 20 %>
              <p><%= link_to ts("See all (%{fandoms_len})", :fandoms_len => @suggested_fandoms.length), {:controller => :tags, :action => :wrangle, :id => @tag, :show => :suggested_fandoms} %></p>
            <% end %>
            </dd>
          <% end %>
          <dt><%= tag_category_name(tag_type) %></dt>
          <dd title="<%= tag_category_name(tag_type) %>" class="tags listbox group">
            <% if @parents[tag_type].present? %>
              <h4 class="heading"><%= ts("Check to remove:") %></h4>
              <%= check_all_none("All", "None", tag_type) %>
              <%= checkbox_section(f, "associations_to_remove", @parents[tag_type], :name_helper_method => "remove_tag_association_label", :extra_info_method => "link_to_edit_tag",
                    :field_id => "parent_#{tag_type}_associations_to_remove", :concise => true) %>
              <h5 class="heading"><%= f.label tag_type.underscore + '_string', ts("Add:") %></h5>
            <% else %>
              <h4 class="heading"><%= f.label tag_type.underscore + '_string', ts("Add %{catname}:", :catname => tag_category_name(tag_type)) %></h4>
            <% end %>
            <div title="<%= ts('add tags') %>">
              <%= f.text_field tag_type.underscore + '_string', autocomplete_options("tag?type=#{(tag_type.downcase == 'metatag' ? @tag.type.downcase : tag_type.downcase)}", :class => 'tags autocomplete') %>
            </div>
          </dd>
        <% end %>
      </dl>
    </fieldset>

    <% if @tag.canonical? %>
      <fieldset>
        <legend><%= ts("Child Tags") %></legend>
        <h3 class="landmark heading"><%= ts("Child Tags") %></h3>
        <p class="actions" role="navigation"><%= link_to ts('wrangle all child tags'), {:controller => :tags, :action => :wrangle, :id => @tag} %></p>
        <dl>
          <% @tag.child_types.each do |tag_type| %>
            <dt><%= tag_category_name(tag_type) %></dt>
            <dd class="tags listbox group">
              <% if @children[tag_type].present? %>
                <h4 class="heading"><%= ts("Check to remove: ") %></h4>
                <%= check_all_none("All", "None", tag_type) %>
                <%= checkbox_section(f, "associations_to_remove", @children[tag_type][0..19], :name_helper_method => "remove_tag_association_label", :extra_info_method => "link_to_edit_tag",
                      :field_id => "child_#{tag_type}_associations_to_remove", :concise => true) %>
                  <% if @children[tag_type].length > 20 %>
                    <p class="actions" role="navigation">
                      <%= link_to ts("See all (%{children_count})", :children_count => @tag.send(tag_type.underscore.pluralize).count), {:controller => :tags, :action => :wrangle, :id => @tag, :show => tag_type.underscore.pluralize} %>
                    </p>
                  <% end %>
                <h5 class="heading"><%= f.label tag_type.underscore + '_string', ts("Add:") %></h5>
              <% else %>
                <h4 class="heading"><%= f.label tag_type.underscore + '_string', ts("Add %{catname}:", :catname => tag_category_name(tag_type)) %></h4>
              <% end %>
              <div title="<%= ts("add tags") %>">
                <%= f.text_field tag_type.underscore + '_string',
      							autocomplete_options("#{tag_type == 'Merger' ? ('noncanonical_tag?type=' + @tag.type.downcase) : (tag_type == 'SubTag' ? @tag.type.downcase : tag_type.downcase)}",
      							:class => 'tags autocomplete') %>
              </div>
            </dd>
          <% end %>
        </dl>
      </fieldset>
    <% end %>

  <% elsif @tag.is_a?(Media) %>
    <p class="actions" role="navigation"><%= link_to ts('See all fandoms'), {:controller => :tags, :action => :wrangle, :id => @tag, :show => 'fandoms'} %></p>
  <% end %>

  <fieldset>
    <legend><%= ts('Taggings Count') %></legend>
    <h3 class="landmark heading"><%= ts('Taggings Count') %></h3>

    <dl>
      <dt><%= f.label :fix_taggings_count, ts('Fix Taggings Count') %></dt>
      <dd>
        <%= f.check_box(:fix_taggings_count) %>&nbsp;
        <p><%= ts('Enable this if the number of taggings on search or wrangle pages needs to be fixed.') %></p>
      </dd>
    </dl>
  </fieldset>

  <fieldset>
    <legend><%= ts('Submit') %></legend>
    <p class="submit actions">
      <%= submit_tag ts('Save changes') %>
    </p>
  </fieldset>
<% end %>

<% if logged_in_as_admin? %>
  <p><%= ts("Last updated by") %> <%= @tag.last_wrangler.try(:login) || '---' %> <%= ts("on") %> <%= @tag.updated_at %></p>
<% end %>
<!--/content-->

<!--subnav-->
<!--/subnav-->

app/views/tags/index.html.erb
<!--SEARCHBROWSE-->
<!--Descriptive page names, messages and instructions-->
<h2 class="heading"><%= ts("Tags") %></h2>
<!--/descriptions-->

<!--subnav-->
<% unless @collection %>
  <ul class="navigation actions" role="navigation">
    <li class="search"><%= render 'tags/search_form' %></li>
    <% if logged_in? %><li><%= link_to ts("Tag Sets"), tag_sets_path %></li><% end %>
    <li><%= span_if_current(ts('Most Popular'), tags_path, params[:show].blank?) %></li>
    <li><%= span_if_current ts('Random'), tags_path(:show => "random") %></li>
  </ul>
<% end %>
<!--/subnav-->

<!--main content-->
<% unless @collection %>
  <h3 class="landmark heading">
    <% if params[:show] == "random" %>
      <%= ts('Browse Random Tags')%>
    <% else %>
      <%= ts('Browse Popular Tags')%>
    <% end %>
  </h3>
<% end %>

<% if @tags %>
  <ul class="tags cloud index group">
    <!--FRONT END REVIEW: these classes are irregular-->
    <% tag_cloud @tags, %w(cloud1 cloud2 cloud3 cloud4 cloud5 cloud6 cloud7 cloud8) do |tag, css_class| %>
      <li><%= link_to_tag_works_with_text(tag, tag.name, :class => css_class.dup) %></li>
    <% end %>
  </ul>
<% end %>
<!--/content-->

app/views/tags/new.html.erb
<!--Descriptive page name, messages and instructions-->
<h2 class="heading"><%= ts('New Tag') %></h2>

<%= error_messages_for :tag %>

<p><%= ts('Once you have created the tag, the attributes that are particular for that tag category will be available for editing.') %></p>

<!--/descriptions-->

<!--subnav-->
<!--/subnav-->

<!--main content-->
<%= form_for @tag, as: :tag, url: { action: "create" }  do |f| %>
  <dl>
    <dt><%= f.label :name, ts('Name') %></dt>
    <dd><%= f.text_field :name, size: ArchiveConfig.TAG_MAX %></dd>

    <dt><%= f.label :canonical, ts('Canonical') %></dt>
    <dd><%= f.check_box :canonical %></dd>

    <dt><%= ts('Category') %></dt>
    <dd>
      <% if logged_in_as_admin? %>
        <% types = Tag::TYPES  %>
      <% else %>
        <% types = Tag::USER_DEFINED %>
      <% end %>
      <ul>
        <% types.each do |type| %>
          <li>
            <%= f.radio_button("type", type) %>
            <%= f.label("type_#{type.downcase}", type) %>
          </li>
        <% end %>
      </ul>
    </dd>
  </dl>

  <p class="submit actions">
    <%= f.submit %>
  </p>
<% end %>
<!--/content-->

<!--subnav-->
<!--/subnav-->

app/views/tags/show.html.erb
<!--ZONES TAG HOME Descriptive page name, messages and instructions-->
<div class="tag home profile">
  <div class="primary header module">
    <h2 class="heading"><%= @tag.name %></h2>
    <div class="icon"></div>
    <% if @tag.canonical || @tag.merger || can_wrangle? %>
      <ul class="navigation actions" role="navigation">
        <% if @tag.canonical || @tag.merger %>
          <li><%= link_to ts('Works'), {:controller => :works, :action => :index, :tag_id => @tag} %></li>
          <li><%= link_to ts('Bookmarks'), {:controller => :bookmarks, :action => :index, :tag_id => @tag} %></li>
        <% end %>
    	<% if can_wrangle? %>
      	  <li><%= link_to ts('Edit'), {:controller => :tags, :action => :edit, :id => @tag} %> </li>
      	  <li><%= tag_comment_link(@tag) %></li>
        <% end %>
        <% if logged_in_as_admin? %>
          <li><%= link_to ts('Reindex Tag'), reindex_tag_path(@tag) %> </li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <%= error_messages_for :tag %>
  <!--/descriptions-->

  <!--main content-->
  <p><%= ts("This tag belongs to the %{tag_class} Category.", :tag_class => @tag.class::NAME) %>
  <% if @tag.canonical %>
    <%= ts("It's a common tag. You can use it to ") %> 
    <%= link_to ts('filter works'), {:controller => :works, :action => :index, :tag_id => @tag} %> <%= ts('and to') %> 
    <%= link_to ts('filter bookmarks'), {:controller => :bookmarks, :action => :index, :tag_id => @tag} %>.
  <% end %>
  </p>
  

  <% if @tag.is_a?(Rating) && @tag.adult %>
  <p class="warning"><%= ts('This tag indicates adult content.') %></p>
  <% end %>

  <% if @tag.is_a?(Fandom) %>
  <div class="parent fandom listbox group">
	  <h3 class="heading"><%= ts('Parent tags (more general)') %>:</h3>
    <ul class="tags commas index group">
	  <% (@tag.parents + [@tag.media]).uniq.compact.sort.each do |parent| %>
      <li><%= link_to_tag parent %></li>
    <% end %>
    </ul>
  </div>
  <% else %>
    <% unless @tag.parents.blank? %>
    <div class="parent listbox group">
      <h3 class="heading"><%= ts('Parent tags (more general)') %>:</h3>
      <ul class="tags commas index group"><%= tag_link_list(@tag.parents.sort) %></ul>
    </div>
    <% end %>
  <% end %>

  <% if @tag.merger %>
  <div class="merger module">
    <h3 class="heading"><%= ts("Mergers") %></h3>
    <p><%= ts("%{tag_name} has been made a synonym of %{tag_synonym_link}. Works and bookmarks tagged with %{tag_name} will show up in %{tag_synonym}'s filter.", :tag_name => @tag.name, :tag_synonym_link => (link_to_tag @tag.merger), :tag_synonym => @tag.merger.name).html_safe %></p>
  </div>
  <% end %>

  <% unless @tag_children['Merger'].blank? %>
  <div class="synonym listbox group">
    <h3 class="heading"><%= ts('Tags with the same meaning') %>:</h3>
    <ul class="tags commas index group"><%= tag_link_list(@tag_children['Merger'].sort) %></ul>
  </div>
  <% end %>

  <% unless @tag.direct_meta_tags.blank? %>
  <div class="meta listbox group">
    <h3 class="heading"><%= ts('Meta tags') %>:</h3>
    <% cache "tag-#{@tag.cache_key}-metatags", :expires_in => 24.hours, skip_digest: true do %>
      <%= meta_tag_tree(@tag) %>
    <% end %>
  </div>
  <% end %>

  <% unless @tag.direct_sub_tags.blank? %>
  <div class="sub listbox group">
    <h3 class="heading"><%= ts('Sub tags') %>:</h3>
    <% cache "tag-#{@tag.cache_key}-subtags", :expires_in => 24.hours, skip_digest: true do %>
      <%= sub_tag_tree(@tag) %>
    <% end %>
  </div>
  <% end %>

  <% unless (@tag_children.keys - ['Merger']).blank? %>
    <!-- caching -->
    <% cache("tag-#{@tag.cache_key}-children-v2", skip_digest: true) do %>
      <div class="child listbox group">
        <h3 class="heading"><%= ts('Child tags (displaying the first %{count} of each type)', :count => ArchiveConfig.TAG_LIST_LIMIT) %>:</h3>
        <% %w(Character Relationship Freeform).each do |type| %>
          <% if @tag_children[type].present? %>
            <div class="<%= type.to_s.pluralize.downcase %> listbox group">
              <h4 class="heading"><%= type.constantize::NAME.pluralize %>:</h4>
              <ul class="tags commas index group">
                <%= tag_link_list(@tag_children[type].sort) %>
                <% if @tag_children[type].length > ArchiveConfig.TAG_LIST_LIMIT %>
                  <li><%= ts("and more") %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  <% end %>

  <% if @works %>
    <p><%= ts("This tag has not been marked common and can't be filtered on (yet).") %></p>  
    <% unless @works.blank? %>
      <div class="work listbox group">
      <h3 class="heading"><%= ts('Works which have used it as a tag') %>:</h3>
      <%= paginated_section @works do %>
          <ul class="index group">
            <% for work in @works %>
              <%= render :partial => 'works/work_blurb', :locals => {:work => work} %>
            <% end %>
          </ul>
        <% end %>
      </div>
    <% end %>

    <% unless @bookmarks.blank? %>
    <div class="bookmark listbox group">
    <h3 class="heading"><%= ts('Bookmarks which have used it as a tag') %>:</h3>
    <%= paginated_section @bookmarks, {:previous_label => '&laquo; Previous', :next_label => 'Next &raquo;'} do %>
        <ul class="index group">
          <% for bookmark in @bookmarks %>
            <%= render 'bookmarks/bookmark_blurb', :bookmark => bookmark %>
          <% end %>
        </ul>
      <% end %>
    </div>
    <% end %>
  <% end %>
</div>
<!--/content-->