config/routes.rb
Otwarchive::Application.routes.draw do

  devise_for :admin,
             module: 'admin',
             only: :sessions,
             controllers: { sessions: 'admin/sessions' },
             path_names: {
               sign_in: 'login',
               sign_out: 'logout'
             }

  devise_scope :user do
    get 'signup(/:invitation_token)' => 'users/registrations#new', as: 'signup'
  end

  devise_for :users,
             module: 'users',
             controllers: {
                sessions: 'users/sessions',
                registrations: 'users/registrations'
              },
              path_names: {
                sign_in: 'login',
                sign_out: 'logout'
              }

  get '/403', to: 'errors#403'
  get '/404', to: 'errors#404'
  get '/422', to: 'errors#422'
  get '/500', to: 'errors#500'
  get '/auth_error', to: 'errors#auth_error'

  get 'downloads/:download_prefix/:download_authors/:id/:download_title.:format' => 'downloads#show', as: 'download'

  namespace :opendoors do
    resources :tools, only: [:index] do
      collection do
        post :url_update
      end
    end
    resources :external_authors do
      member do
        post :forward
      end
    end
  end

  resources :invitations
  resources :user_invite_requests
  resources :invite_requests do
    collection do
      get :manage
      post :reorder
      get :status
    end
  end

  get 'claim/:invitation_token' => 'external_authors#claim', as: 'claim'
  post 'complete_claim/:invitation_token' => 'external_authors#complete_claim', as: 'complete_claim'

  resources :media do
    resources :fandoms
  end
  resources :fandoms do
    collection do
      get :unassigned
    end
    get :show
  end
  resources :tag_wranglings do
    collection do
      post :wrangle
      get :discuss
    end
  end
  resources :tag_wranglers
  resources :unsorted_tags do
    collection do
      post :mass_update
    end
  end
  resources :tags do
    member do
      get :feed
      post :mass_update
      get :remove_association
      get :wrangle
      get :reindex
    end
    collection do
      get :show_hidden
      get :search
    end
    resources :works
    resources :bookmarks
    resources :comments
  end

  resources :tag_sets, controller: 'owned_tag_sets' do
    resources :nominations, controller: 'tag_set_nominations' do
      collection do
        put  :update_multiple
        delete :destroy_multiple
        get :confirm_destroy_multiple
      end
      member do
        get :confirm_delete
      end
    end
    resources :associations, controller: 'tag_set_associations', only: [:index] do
      collection do
        put :update_multiple
      end
    end
    member do
      get :batch_load
      put :do_batch_load
      get :confirm_delete
    end
    collection do
      get :show_options
    end
  end
  resources :tag_nominations, only: [:update]

  resources :tag_wrangling_requests, only: [:index] do
    collection do
      patch :update_multiple
    end
  end

  resources :admins
  resources :admin_posts do
    resources :comments
  end

  namespace :admin do
    resources :activities, only: [:index, :show]
    resources :banners do
      member do
        get :confirm_delete
      end
    end
    resources :blacklisted_emails, only: [:index, :new, :create, :destroy]
    resources :settings
    resources :skins do
      collection do
        get :index_rejected
        get :index_approved
      end
    end
    resources :spam, only: [:index] do
      collection do
        post :bulk_update
      end
    end
    resources :user_creations, only: [:destroy] do
      member do
        put :hide
        put :set_spam
      end
    end
    resources :users, controller: 'admin_users' do
      member do
        get :confirm_delete_user_creations
        post :destroy_user_creations
        post :activate
        post :send_activation
        get :check_user
      end
      collection do
        get :bulk_search
        post :bulk_search
        post :update_user
      end
    end
    resources :invitations, controller: 'admin_invitations' do
      collection do
        post :invite_from_queue
        post :grant_invites_to_users
        get :find
      end
    end
    resources :api
  end

  post '/admin/api/new', to: 'admin/api#create'

  resources :people, only: [:index] do
    collection do
      get :search
    end
  end

  resources :passwords, only: [:new, :create]

  resources :users, except: [:new, :create] do
    member do
      get :browse
      get :change_email
      post :changed_email
      get :change_password
      post :changed_password
      get :change_username
      post :changed_username
      post :end_first_login
      post :end_banner
      post :end_tos_prompt
    end
    resources :assignments, controller: "challenge_assignments", only: [:index] do
      collection do
        patch :update_multiple
      end
      member do
        get :default
      end
    end
    resources :claims, controller: "challenge_claims", only: [:index]
    resources :bookmarks
    resources :collection_items, only: [:index, :update, :destroy] do
      collection do
        patch :update_multiple
      end
    end
    resources :collections, only: [:index]
    resources :comments do
      member do
        put :approve
        put :reject
      end
    end
    resources :external_authors do
      resources :external_author_names
    end
    resources :favorite_tags, only: [:create, :destroy]
    resources :gifts, only: [:index]
    resource :inbox, controller: "inbox" do
      member do
        get :reply
        post :delete
      end
    end
    resources :invitations do
      collection do
        post :invite_friend
      end
      collection do
        get :manage
      end
    end
    resources :nominations, controller: "tag_set_nominations", only: [:index]
    resources :preferences, only: [:index, :update]
    resource :profile, only: [:show], controller: "profile"
    resources :pseuds do
      resources :works
      resources :series
      resources :bookmarks
    end
    resources :readings do
      collection do
        post :clear
      end
    end
    resources :related_works
    resources :series do
      member do
        get :manage
      end
      resources :serial_works
    end
    resources :signups, controller: "challenge_signups", only: [:index]
    resources :skins, only: [:index]
    resources :stats, only: [:index]
    resources :subscriptions, only: [:index, :create, :destroy]
    resources :tag_sets, controller: "owned_tag_sets", only: [:index]
    resources :works do
      collection do
        get :drafts
        get :collected
        get :show_multiple
        post :edit_multiple
        patch :update_multiple
        post :delete_multiple
      end
    end
  end

  resources :works do
    collection do
      post :import
      get :search
    end
    member do
      get :preview
      post :post
      put :post_draft
      get :navigate
      get :edit_tags
      get :preview_tags
      patch :update_tags
      get :mark_for_later
      get :mark_as_read
      get :confirm_delete
      get :reindex
    end
    resources :bookmarks
    resources :chapters do
      collection do
        get :manage
        post :update_positions
      end
      member do
        get :preview
        post :post
        get :confirm_delete
      end
      resources :comments
    end
    resources :collections
    resources :collection_items
    resources :comments do
      member do
        put :approve
        put :reject
      end
      collection do
        get :unreviewed
        put :review_all
      end
    end
    resources :kudos, only: [:index]
    resources :links, controller: "work_links", only: [:index]
  end

  resources :chapters do
    member do
      get :preview
      post :post
    end
    resources :comments
  end

  resources :external_works do
    collection do
      get :compare
      post :merge
      get :fetch
    end
    resources :bookmarks
    resources :related_works
  end

  resources :related_works
  resources :serial_works
  resources :series do
    member do
      get :confirm_delete
      get :manage
      post :update_positions
    end
    resources :bookmarks
  end

  resources :gifts, only: [:index] do
    member do
      post :toggle_rejected
    end
  end

  resources :collections do
    collection do
      get :list_challenges
      get :list_ge_challenges
      get :list_pm_challenges
    end
    member do
      get :confirm_delete
    end
    resource :profile, controller: "collection_profile"
    resources :collections
    resources :works
    resources :gifts
    resources :bookmarks
    resources :media
    resources :fandoms
    resources :people
    resources :prompts
    resources :tags do
      resources :works
    end
    resources :participants, controller: "collection_participants" do
      collection do
        get :add
        get :join
        patch :update
      end
    end
    resources :items, controller: "collection_items" do
      collection do
        patch :update_multiple
      end
    end
    resources :signups, controller: "challenge_signups" do
      collection do
        get :summary
      end
      member do
        get :confirm_delete
      end
    end
    resources :assignments, controller: "challenge_assignments", except: [:new, :edit, :update] do
      collection do
        get :confirm_purge
        get :generate
        put :set
        post :purge
        get :send_out
        put :update_multiple
        get :default_all
      end
    end
    resources :claims, controller: "challenge_claims" do
      collection do
        patch :set
        get :purge
      end
    end
    resources :potential_matches do
      collection do
        get :generate
        get :cancel_generate
        get :regenerate_for_signup
      end
    end
    resources :requests, controller: "challenge_requests"

app/controllers/admin/admin_invitations_controller.rb
class Admin::AdminInvitationsController < ApplicationController

  before_action :admin_only

  def index
  end

  def create
    @invitation = current_admin.invitations.new(invitation_params)
    if @invitation.invitee_email.blank?
      flash[:error] = t('no_email', default: "Please enter an email address.")
      render action: 'index'
    elsif @invitation.save
      flash[:notice] = t('sent', default: "An invitation was sent to %{email_address}", email_address: @invitation.invitee_email)
      redirect_to admin_invitations_path
    else
      render action: 'index'
    end
  end

  def invite_from_queue
    InviteRequest.order(:position).limit(invitation_params[:invite_from_queue].to_i).each do |request|
      request.invite_and_remove(current_admin)
    end
    InviteRequest.reset_order
    flash[:notice] = t('invited_from_queue', default: "%{count} people from the invite queue were invited.", count: invitation_params[:invite_from_queue].to_i)
    redirect_to admin_invitations_path
  end

  def grant_invites_to_users
    if invitation_params[:user_group] == "All"
      Invitation.grant_all(invitation_params[:number_of_invites].to_i)
    else
      Invitation.grant_empty(invitation_params[:number_of_invites].to_i)
    end
    flash[:notice] = t('invites_created', default: 'Invitations successfully created.')
    redirect_to admin_invitations_path
  end

  def find
    unless invitation_params[:user_name].blank?
      @user = User.find_by(login: invitation_params[:user_name])
      @hide_dashboard = true
      @invitations = @user.invitations if @user
    end
    if !invitation_params[:token].blank?
      @invitation = Invitation.find_by(token: invitation_params[:token])
    elsif !invitation_params[:invitee_email].blank?
      @invitations = Invitation.where('invitee_email LIKE ?', "%#{invitation_params[:invitee_email]}%")
      @invitation = @invitations.first if @invitations.length == 1
    end
    unless @user || @invitation || @invitations
      flash.now[:error] = t('user_not_found', default: "No results were found. Try another search.")
    end
  end

  private

  def invitation_params
    params.require(:invitation).permit(:invitee_email, :invite_from_queue,
      :user_group, :number_of_invites, :user_name, :token)
  end
end

app/views/admin/admin_invitations/find.html.erb
<!--Descriptive page name, messages and instructions-->
<h2 class="heading"><%h= 'Track invitations' %></h2>
<!--/descriptions-->

<!--subnav-->
<!--/subnav-->

<!--main content-->
<%= form_tag url_for(:controller => 'admin/admin_invitations', :action => 'find'), :method => :get do %>
  <dl>
    <dt><%= label_tag :user_name, t('.find_user_name', :default => 'Enter a user name:') %></dt>
    <dd><%= text_field_tag "invitation[user_name]", params[:invitation][:user_name]  %></dd>
    <dt><%= label_tag :token, t('.find_token', :default => 'Enter an invite token:') %></dt>
    <dd><%= text_field_tag "invitation[token]", params[:invitation][:token]  %></dd>
    <dt><%= label_tag :invitee_email, t('.find_email', :default => 'Enter all or part of an email address:') %></dt>
    <dd><%= text_field_tag "invitation[invitee_email]", params[:invitation][:invitee_email], id: "invitee_email"  %></dd>
  </dl>
  <p class="submit actions"><%= submit_tag "Go" %></p>
<% end %>

<% if @user %>
<h3 class="heading"><%h= 'Invitations for' %> <%= link_to @user.login, user_invitations_path(@user) %></h3>
<%= render :partial => 'invitations/user_invitations', :locals => {:invitations => @invitations} %>
<% elsif @invitation %>
<%= render :partial => 'invitations/invitation', :locals => {:invitation => @invitation} %>
<% elsif @invitations %>
<%= render :partial => 'invitations/user_invitations', :locals => {:invitations => @invitations} %>
<% end %>
<!--/content-->

<!--subnav-->
<!--/subnav-->

app/views/admin/admin_invitations/index.html.erb
<!--Descriptive page name, messages and instructions-->
<h2 class="heading"><%=h ts("Invite new users") %></h2>
<!--/descriptions-->
<!--subnav-->
<ul class="navigation actions" role="navigation">
  <li><%= link_to "Manage requests", user_invite_requests_path %></li>
  <li><%= link_to "Manage queue", manage_invite_requests_path %></li>
</ul>
<!--/subnav-->
<!--main content-->
<%= form_tag  url_for(:controller => 'admin/admin_invitations', :action => :create) do |f| %>
  <fieldset class="simple">
    <h3 class="heading">Send to email</h3>
    <p>Send an invite code to the following email address:
      <%= text_field_tag "invitation[invitee_email]", (@invitation.try(:invitee_email) || ""), :title => ts("invite by email") %>
      <span class="submit actions"><%= submit_tag ts('Invite user')  %></span>
    </p>
  </fieldset>
<% end %>

<%= form_tag url_for(:controller => 'admin/admin_invitations', :action => 'invite_from_queue') do %>
  <fieldset class="simple">
    <h3 class="heading">Send invite codes to people in our <%= link_to 'invitations queue', invite_requests_path %></h3>
    <p>There are <%= InviteRequest.count %> requests in the queue.</p>
    <p>
      <%= label_tag "invitation[invite_from_queue]", ts('Number of people to invite') %>: <%= text_field_tag "invitation[invite_from_queue]" %>
      <span class="submit actions"><%= submit_tag ts('Invite from queue')  %></span>
    </p>
  </fieldset>
<% end %>

<%= form_tag  url_for(:controller => 'admin/admin_invitations', :action => 'grant_invites_to_users') do  %>
  <fieldset>
    <h3 class="heading"><%=h 'Give invite codes to current users' %></h3>
    <dl>
      <dt><%= label_tag "invitation[number_of_invites]", ts('Number of invitations') %>:</dt>
      <dd><%= text_field_tag "invitation[number_of_invites]" %></dd>
      <dt><%= label_tag "invitation[user_group]", ts('Users') %>:</dt>
      <dd><%= select_tag "invitation[user_group]", "<option>All</option><option>With no unused invitations</option>".html_safe  %></dd>
      <dt class="landmark">Submit</dt>
      <dd class="submit actions"><%= submit_tag "Generate invitations" %></dd>
  </fieldset>
<% end %>

<%= form_tag  url_for(:controller => 'admin/admin_invitations', :action => 'find'), :method => :get do  %>
  <fieldset>
    <h3 class="heading"><%=h 'Track invitations' %></h3>
    <dl>
      <dt><%= label_tag "invitation[user_name]", ts('Enter a user name') %>:</dt>
      <dd><%= text_field_tag "invitation[user_name]"  %></dd>
      <dt><%= label_tag "invitation[token]", ts('Enter an invite token') %>:</dt>
      <dd><%= text_field_tag "invitation[token]"  %></dd>
      <dt><%= label_tag "invitation[invitee_email]", ts('Enter all or part of an email address') %>:</dt>
      <dd><%= text_field_tag "invitation[invitee_email]", nil, id: "track_invitation_invitee_email" %></dd>
      <dt class="landmark">Submit</dt>
      <dd class="submit actions"><%= submit_tag "Go" %></dd>
    </dl>
  </fieldset>
<% end %>
<!--/content-->

app/views/admin/admin_invitations/new.html.erb
<!--Descriptive page name, messages and instructions-->
<h2 class="heading"><%= t('.invite_user', :default => "Invite a User") %></h2>
<!--/descriptions-->

<!--subnav-->
<!--/subnav-->

<!--main content-->
<%= form_for :invitation, @invitation, :url => { :controller => 'admin/admin_invitations', :action => :create } do |f| %>
    <p><%= f.label :recipient_email, t('.email_address', :default => "Email address") %> <%= f.text_field :recipient_email %></p>
    <p class="submit actions"><%= f.submit t('.submit', :default => "Invite!") %></p>
<% end %>
<!--/content-->

<!--subnav-->
<!--/subnav-->